name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Download and Extract Official Full NCNN Vulkan SDK
      run: |
        # 创建一个临时的下载目录
        mkdir -p ncnn_download
        cd ncnn_download
        
        # 1. 直接下载腾讯 NCNN 官方最新满血稳定版的 Android Vulkan SDK 压缩包
        curl -L -o ncnn-android-vulkan.zip https://github.com/Tencent/ncnn/releases/download/20240410/ncnn-20240410-android-vulkan.zip
        
        # 2. 原地解压它
        unzip ncnn-android-vulkan.zip
        
        # 3. 强行把解压出来的满血静态库文件（包含所有 glslang 依赖组件）拷贝覆盖到项目中
        TARGET_LIB_DIR="../app/src/main/cpp/ncnn_sdk/libs/arm64-v8a"
        mkdir -p $TARGET_LIB_DIR
        cp -f ncnn-20240410-android-vulkan/arm64-v8a/lib/*.a $TARGET_LIB_DIR/
        
        # 4. 验证一下，此时里面一定会整整齐齐躺着所有官方编译好的 .a 文件
        cd ..
        ls -lh app/src/main/cpp/ncnn_sdk/libs/arm64-v8a/

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
